### ISSUE TITLE
Bug when no HTTP_REFERER and change the number of links per page

### ISSUE THREAD

**Issue by Oros42** [shaarli/Shaarli#824] opened 2017-03-17 10:17 UTC
When the browser does not send HTTP_REFERER and you wants to change the number of links per page (linksperpage=...), then you got :
```
PHP Notice:  Undefined index: HTTP_REFERER in .../shaarli/index.php on line 1026
```
Quick fix line 1026:
```
header('Location: '. generateLocation(empty($_SERVER['HTTP_REFERER'])?"":$_SERVER['HTTP_REFERER'], $_SERVER['HTTP_HOST'], array('linksperpage')));
```

In index.php, $_SERVER['HTTP_REFERER'] is use 13 time. So I think it's better to check in one place if $_SERVER['HTTP_REFERER'] is defined or not for all the code.
We can do this type of function : 
```
function getReferer(){
    return empty($_SERVER['HTTP_REFERER'])?"":$_SERVER['HTTP_REFERER'];
}
```

**Comment by ArthurHoaro** [comment] 2017-03-17 10:24
This is a duplicate of #723 (fixed in #761). 

As for your solution, it is a bit cleaner, but all of this will be refactored in the future and `$_SERVER` will be accessed using Slim container.

**Closed by ArthurHoaro** 2017-03-17 10:24 UTC
Labels: duplicate
