### ISSUE TITLE
[Feature Request] Multiple tag searching

### ISSUE THREAD

**Issue by bonnebulle** [shaarli/Shaarli#1797] opened 2021-09-06 11:11 UTC
Hello 
On my Shaarli ([here](https://liens.vincent-bonnefille.fr/)) I would like to make multiple tag searching...
A way to allow users to search searchtags="XXX" **or** "YYYY" ( || )
not searchtags="XXX" **and** "YYYY" (like actualy do) ( && )

For my use of Shaarli this conditional option will help user finding more contents (or affiliate content)

And exemple of multiple "sub-category" of tags, a situation where, mutiple tag searching can help finding all :
![Capture d’écran 2021-09-06 à 12 43 33](https://user-images.githubusercontent.com/1598041/132207830-a98e8066-cf07-4927-88dd-3b7ef9870620.png)

I already remove the addtag function on clicking them...
But, here, I dont know how to add this feature

**Comment by nodiscc** [comment] 2021-09-06 20:18
Hi,
duplicate of https://github.com/shaarli/Shaarli/issues/968 ?

**Closed** 2021-09-23 06:32 UTC
Labels: feedback needed
