### ISSUE TITLE
Export bookmarks : invalid token

### ISSUE THREAD

**Issue by Quentin-ctrL** [shaarli/Shaarli#1814] opened 2021-12-04 14:17 UTC
Hi,

I'm trying to export my bookmarks via the web UI
Depending, I get nothing or error message 'invalid token'

No success using shaarchiver or bash script 
Deactivating plugins doesn't help

Shaarli 0.12.1
PHP 7.3.31 

edit: I tried to backup and install new shaarli, the issue still persis

**Comment by ekkipatang** [comment] 2021-12-17 11:00
Hi, same here

Shaarli 0.12.1
PHP 7.3.31

**Comment by nodiscc** [comment] 2021-12-17 14:20
Hi,

>  Depending, I get nothing or error message 'invalid token'
> I'm trying to export my bookmarks via the web UI

I can't reproduce this, Shaarli 0.12.1 installed from release zip, php-fpm 2:7.3+69, apache 2.4.51-1~bpo10+2, Debian 10

> No success using shaarchiver or bash script

shaarchiver is unmaintained, I plan to rewrite it to use the REST API and add features but don't have time

@Quentin-ctrL @ekkipatang which [installation method](https://shaarli.readthedocs.io/en/master/Installation/) are you using? Do you have any relevant message in browser/webserver/php-fpm logs? Have you installed any third-party plugins/themes?

**Comment by Quentin-ctrL** [comment] 2021-12-20 11:46
installation method : from zip

I tried without plugins/themes, same issue.

Sorry, I didn't check logs. I'll check when I can.
As workaround, I used REST API.

**Comment by nodiscc** [comment] 2022-04-23 12:10
@Quentin-ctrL do you still have this problem? Can you check your logs when it happens?

**Comment by nodiscc** [comment] 2022-11-20 15:18
No reply for > 6 months, closing.

**Closed by nodiscc** 2022-11-20 15:18 UTC
Labels: bug, unconfirmed, feedback needed, support
