### ISSUE TITLE
lighttpd - shaare fails when urlencoded string contains %0A

### ISSUE THREAD

**Issue by andreworg** [shaarli/Shaarli#1703] opened 2021-02-02 15:12 UTC
shaare action fails when the urlencoded string used in the GET contains `%0A`.
This happens to me when selecting more than one paragraph of text then using the "+Shaare link" bookmarklet.

Examples:

https://my.shaarli/ndex.php/admin/shaare?post=https%3A%2F%2Fmysite.com&title=my%20title&description=my%20description
OK
https://my.shaarli/ndex.php/admin/shaare?post=https%3A%2F%2Fmysite.com&title=my%20title&description=my%0Adescription
400 Bad Request
https://my.shaarli/ndex.php/admin/shaare?post=https%3A%2F%2Fmysite.com&title=my%0Atitle&description=my%20description
400 Bad Request

**Comment by nodiscc** [comment] 2021-02-02 16:49
Cannot reproduce this bug at  https://demo.shaarli.org/admin/shaare?post=https%3A%2F%2Fmysite.com&title=my%20title&description=my%0Adescription or https://demo.shaarli.org/admin/shaare?post=https%3A%2F%2Fmysite.com&title=my%0Atitle&description=my%20description

@andreworg can you tell us more about your setup?
- Shaarli version
- Installation method
- Web server and PHP interpreter
- Relevant webserver error logs
- Relevant configuration (please check https://shaarli.readthedocs.io/en/master/Server-configuration/ and other pages)

**Comment by andreworg** [comment] 2021-02-03 15:41
Thank you @nodiscc, you're right, I should have seen this error was coming from the webserver.
Definitely looks like it's due to [lighttpd's HTTP request parsing and normalization options](https://redmine.lighttpd.net/boards/2/topics/8610) I did not know about.
I'll look into this and report the needed configuration option in case someone else stumbles upon this.

**Comment by andreworg** [comment] 2021-02-03 16:14
This configuration option in lighttpd.conf solves the issue:

`server.http-parseopts = ( "url-ctrls-reject" => "disable")`

Maybe this could be added in the docs, I see a section for lighttpd is currently missing.
I could do this myself, but I think it should also include the configuration for URL rewriting, and I still haven't implemented it (to be honest I'm quite fine without it).

**Comment by nodiscc** [comment] 2021-02-03 16:53
Adding an example lighttpd configuration to https://github.com/shaarli/Shaarli/blob/master/doc/md/Server-configuration.md would be welcome. If you don't have a working URL rewriting setup just mention it in the example.

If the immediate problem is solved then I guess we can close this issue. Thanks for reporting!

**Closed by nodiscc** 2021-02-03 16:53 UTC
Labels: feedback needed, support
