### ISSUE TITLE
Shaarli "farm"/multiple user accounts management tool

### ISSUE THREAD

**Issue by qwertygc** [shaarli/Shaarli#204] opened 2015-04-27 10:42 UTC
Hello !
DMeloni et moi même avaient fait des fermes à shaarli en modifiant quelques lignes de code. Vu que c'est rébarbatif de refaire à chaque maj, c'est possible de faire une option pour permettre de faire un multishaarli ?
Cordialement,
Les modifications : 
https://github.com/qwertygc/Shaarli/commit/4a30e26433134d757a5ec81d338e829a3256dcc9
https://github.com/qwertygc/Shaarli/commit/416ad20c886c1b96f1c29f23f7fcdb772db0e3be
https://github.com/qwertygc/Shaarli/commit/b297fdf96301bcaa97efc3ac980fc84e1a4cefd5

**Comment by nodiscc** [comment] 2015-04-27 11:09
Duplicate of https://github.com/shaarli/Shaarli/issues/15 ?

**Comment by qwertygc** [comment] 2015-04-27 11:57
1) Maintabilité du code
2) cette solution est plus légère.

**Comment by nodiscc** [comment] 2015-04-27 17:15
Shaarli is single-directory (1 directory=1 shaarli instance=1user), so user account management can easily be left to an other tool. 

This also brings less problems than letting users write an arbitrary arbitrary string in  `$GLOBALS['config']['DATADIR']` (https://github.com/qwertygc/Shaarli/commit/b297fdf96301bcaa97efc3ac980fc84e1a4cefd5#diff-828e0013b8f3bc1bb22b4f57172b019dR25) and doing mkdirs and chmods with this var (https://github.com/qwertygc/Shaarli/commit/b297fdf96301bcaa97efc3ac980fc84e1a4cefd5#diff-828e0013b8f3bc1bb22b4f57172b019dR2113)...

This bash script works https://github.com/nodiscc/scriptz/blob/master/sysadmin/shaarlifarm.sh, let me know if you think of possible improvements (for example it could take care of auto-updates). Just edit the config values and run the script on your host.

If you want to manage multiple shaarlis/user accounts from a web interface, please do but it should be in a separate tool. I think this project does it already: https://www.shaarli.fr/my.php

```
$ ./shaarlifarm.sh 
[info] account bob already exists, skipping
[info] account john already exists, skipping
[info] creating new account myshaarli ...
[info] creating new account whatever ...
[info] generating new index of shaarlis
[info] done.
[info] list of accounts: bob john maurice whatever
[info] contents of /var/www/shaarli:
/var/www/shaarli
├── bob
├── index.html
├── john
├── myshaarli
└── whatever

4 directories, 1 file
```

**Comment by virtualtam** [comment] 2017-02-25 17:51
This has been done by [Framasoft](https://framasoft.org/) on [MyFrama](https://my.framasoft.org/), which is based on Shaarli. The corresponding code can be found on [Framasoft/MyFrama](https://framagit.org/framasoft/myframa/tree/master).

**Closed** 2017-02-25 18:51 UTC
Labels: 3rd party, project-related
