### ISSUE TITLE
Can't login after upgrade PHP

### ISSUE THREAD

**Issue by Cyrixo** [shaarli/Shaarli#770] opened 2017-01-20 15:31 UTC
Hello;
I can't login  ( page blank ) after upgrade system. ( php 7.0.14-1 -> 7.1.1-1 )
In the error log
`PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function ban_canLogin(), 0 passed in /srv/http/liens/tmp/loginform.9097c979923185181c80a7f04e7d4686.rtpl.php on line 5 and exactly 1 expected in /srv/http/liens/index.php:383\nStack trace:\n#0 /srv/http/liens/tmp/loginform.9097c979923185181c80a7f04e7d4686.rtpl.php(5): ban_canLogin()\n#1 /srv/http/liens/inc/rain.tpl.class.php(175): include('/srv/http/liens...')\n#2 /srv/http/liens/application/PageBuilder.php(134): RainTPL->draw('loginform')\n#3 /srv/http/liens/index.php(800): PageBuilder->renderPage('loginform')\n#4 /srv/http/liens/index.php(2219): renderPage(Object(ConfigManager), Object(PluginManager))\n#5 {main}\n  thrown in /srv/http/liens/index.php on line 383,`

Have you an idea ?

Edit : Running Archlinux

**Comment by CountMurphy** [comment] 2017-01-20 15:32
Same issue here. Running on Arch Linux

**Comment by ArthurHoaro** [comment] 2017-01-20 15:38
Duplicate of #711 

It may have been a good idea to release the fix however... Especially since Arch repos updated, and the v0.9.0 isn't planned so soon. I'll make a v0.8.3 with the fix *cherry-picked*.

**Comment by ArthurHoaro** [comment] 2017-01-20 15:57
Please use [v0.8.3](https://github.com/shaarli/Shaarli/releases/tag/v0.8.3) which should fix your issue.

**Closed by ArthurHoaro** 2017-01-20 15:57 UTC
Labels: duplicate, php compatibility, support

**Comment by Cyrixo** [comment] 2017-01-20 17:00
Thank you very much for your work. It's OK with 0.8.3.

**Comment by q2apro** [comment] 2017-12-08 10:07
Upgraded from 0.8.0 to 0.9.0 - issue still persists: 

`Uncaught ArgumentCountError: Too few arguments to function ban_canLogin(), 0 passed in shaarli/tmp/loginform.9097c979923185181c80a7f04e7d4686.rtpl.php on line 5 and exactly 1 expected in shaarli/index.php:383 Stack trace: #0 shaarli/tmp/loginform.9097c979923185181c80a7f04e7d4686.rtpl.php(5): ban_canLogin() #1 shaarli/inc/rain.tpl.class.php(175): include('/srv/users/serv...') #2 shaarli/application/PageBuilder.php(134): RainTPL->draw('loginform') #3 shaarli/index.php(800): PageBuilder->renderPage('loginform') #4 shaarli/index.php(2219): renderPage(Object(ConfigManager), Object(PluginManager)) #5 {main} thrown in shaarli/index.php on line 383`

Can you post the fix?

**Comment by nodiscc** [comment] 2017-12-09 14:47
@q2apro what upgrade method did you use? Was `shaarli/tmp/` directory emptied during upgrades?

**Comment by q2apro** [comment] 2017-12-09 15:05
I actually did a fresh install.

**Comment by ArthurHoaro** [comment] 2017-12-11 17:47
Are you using a custom theme?
