### ISSUE TITLE
Current master seems broken to me.

### ISSUE THREAD

**Issue by fbartels** [shaarli/Shaarli#241] opened 2015-06-24 10:23 UTC
Hi,

I just pulled in the recent changes and then noticed that Shaarli stoppen working for me. I did not yet have the time to pinpoint the exact commit that broke it for me, but reverting back to 25c46408a3d5101801574703775cdfd2a0df8d4f (e.g. git reset --hard 25c46408a3d5101801574703775cdfd2a0df8d4f) fixed it for the moment.

This is the error I have in my Apache error.log:
```mod_fcgid: stderr: PHP Parse error:  syntax error, unexpected '[' in /var/www/clients/client1/web35/web/application/LinkDB.php on line 306```

**Comment by nodiscc** [comment] 2015-06-25 16:21
I can't reproduce this (apache 2.4 with mod_php).

[Line 306](https://github.com/shaarli/Shaarli/blob/master/application/LinkDB.php#L306) `$keys = ['title', 'description', 'url', 'tags'];` looks ok to me, no missing closing brackets/quotes before it.

@fbartels can you re-clone an test again? Make sure your local copy is an exact clone of the repo. I would try with mod_fcgid but unfortunately I don't have it set up at the moment.

**Comment by fbartels** [comment] 2015-06-26 05:26
Hi @nodiscc ,

I just did a fresh checkout and walked through the commit history of the last days (Oldest first starting with 4de71445d3d174b5ef3462a1c4470a95cc00017e). 

Starting with 38a0c256d200df872990f6ed450aceaf215eeafd I only get a white page and the already posted error.

```
php -v
PHP 5.3.3-7+squeeze26 with Suhosin-Patch (cli) (built: Apr 29 2015 18:51:11) 
Copyright (c) 1997-2009 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies
    with Suhosin v0.9.32.1, Copyright (c) 2007-2010, by SektionEins GmbH
```

**Comment by fbartels** [comment] 2015-06-26 14:59
Ah, found this issue and created a pull request #249 .

**Comment by nodiscc** [comment] 2015-06-26 20:29
Thanks for the patch, see #249, #250

**Closed by nodiscc** 2015-06-26 20:29 UTC
Labels: bug, please test, unconfirmed
