### ISSUE TITLE
import from diigo in netscape bookmark format fails

### ISSUE THREAD

**Issue by valentt** [shaarli/Shaarli#741] opened 2017-01-05 12:18 UTC
After exporting diigo bookmarks in Netscape bookmark format import fails with message "unknown format".

Is importing from Diigo working or is it currently broken?

**Comment by ArthurHoaro** [comment] 2017-01-05 15:05
Probable duplicate of #681

**Comment by valentt** [comment] 2017-01-05 15:35
Could be a duplicate, I had 2.3MB htm file exported from Diigo. Any chance of applying these nginx changes to demo server?

**Comment by ArthurHoaro** [comment] 2017-01-05 15:41
I don't think it's due the filesize limit, but the probable remaining parsing errors, as mention at the end of the thread. Could you post, or try with, the first few links of your import file?

**Comment by ArthurHoaro** [comment] 2017-03-11 13:49
Hi @valentt, we've added an import log to debug imports in the master branch.

You can use it by:

  - getting the master branch
  - running `composer install`
  - add this in `data/config.json.php`
```
"dev": {
  "debug": true
},
```
  - run your import
  - check out `data/import.date.log` file

Or you can wait for the next release if you prefer.

**Comment by virtualtam** [comment] 2017-10-12 19:16
Closing due to lack of feedback, feel free to reopen should the issue happen again.

**Closed by virtualtam** 2017-10-12 19:16 UTC
Labels: bug, duplicate, support
