### ISSUE TITLE
Adding link does not show edit link dialog (hosting provider with cPanel)

### ISSUE THREAD

**Issue by ShawnPConroy** [shaarli/Shaarli#1027] opened 2017-11-17 18:11 UTC
In a fresh install I click `+ Shaare`, pasting the URL (let's say https://gitter.im/shaarli/Shaarli), and click `Add link`. This sends me to the main link list page, instead of showing the `Edit link` dialog. The URL displayed in my browser address bar at this point is `?post=https%3A%2F%2Fgitter.im%2Fshaarli%2FShaarli#`.

What should have happened is the `Edit link` dialog should have appeared.

I get no errors in my cPanel error log.

I'm using the full zip file. I extract it at the root of my subdomain. I have deleted and retried it with the same results. Originally I had a theme, but later I used a clean install.

## Technical details
* Shaarli: 0.9.2
* Apache Version: 2.2.31
* PHP Version: 5.6.30
* Architecture: x86_64
* Operating System: linux

**Comment by nodiscc** [comment] 2017-11-17 23:05
>  I have deleted and retried it with the same results. Originally I had a theme, but later I used a clean install.

To rule out a browser problem, does it work as expected on the [Shaarli demo instance](https://demo.shaarli.org/?page=3)?

Is it possible that some caching mechanism (server or client side) is interfering?

 * Does clearing the browser cache (or visiting your install in a new Private Browsing session or in another browser) solve the problem?
 * Are you able to [clear the PHP cache](https://stackoverflow.com/questions/911158/how-to-clear-apc-cache-entries) on your host, and does it solve the problem?

**Comment by ArthurHoaro** [comment] 2017-11-18 11:37
That's a surprising issue. If the URL stays `?post=...` it means that it's probably not a session related issue, otherwise you may have seen the linklist but after a redirection, so the URL would have changed.

Did you try with another browser? Ideally one without any extension enabled.

If the problem stays the same after that and @nodiscc suggestion, can you give us the result of the following steps:

  * Click on `+ Shaare` and type anything
  * Edit `[index.php:1407](https://github.com/shaarli/Shaarli/blob/master/index.php#L1407)` and add the following lines:

```php
var_dump($targetPage);
var_dump($_GET);
var_dump($_POST);
die;
```

  * Click on `Add link`.

**Comment by ShawnPConroy** [comment] 2017-11-18 20:51
> Is it possible that some caching mechanism (server or client side) is interfering?

Yes, this is the problem. When I bypass the server cache system it works fine. I'm actually unclear why this is an issue. I expect this is related to NGINX caching, as when I bypass that with a specific port number Shaari seems to work as usual.

It's unclear to me why it would cause a problem at this point, and no other. Set up, import and editing links worked. Just not adding new ones.

**Comment by ArthurHoaro** [comment] 2017-12-12 18:06
You mentioned Apache in your first comment and now nginx ; can you provide more information about your configuration, especially about the cache?

**Comment by ShawnPConroy** [comment] 2017-12-12 18:42
cPanel Version | 62.0 (build 35)
Apache Version | 2.2.31
PHP Version | 5.6.30
MySQL Version | 5.5.51-38.2
Architecture | x86_64
Operating System | linux
Dedicated IP Address | 143.95.43.99
Path to Sendmail | /usr/sbin/sendmail
Path to Perl | /usr/bin/perl
Perl Version | 5.10.1
Kernel Version | 3.10.0-614.10.2.lve1.4.50.el6h.x86_64

In my cPanel I have a Cache Settings option. It brings me to a page with the NGINX logo. It says:

> NGINX is a web serving application that is significantly faster than Apache. NGINX caches your pages, helps with high traffic, and bursting situations. If you are in the development stage of your website, it is recommended you turn this off.

It appears to be on my server, and controllable per domain. Rather than a proxy or ahead of the server intercepting requests ahead of time. I cannot find out what version my host is using. Using port 8080 I can bypass the cache.

But I don't know anymore about the caching system than that. It's a host I have a reseller account with that I provide basic serving to others. They also use SSD (along with NGINX caching) for speed. But the server is, in fact, Apache.

I also didn't realize that I had to manually upgrade my PHP version on each domain.

**Comment by ArthurHoaro** [comment] 2017-12-16 12:31
Unfortunately, as cPanel isn't free and I don't know how it handles its nginx caching system, I don't have any way to reproduce your issue. 

Anyway, it seems rather to be a server configuration issue and not directly related to Shaarli. I suggest that you report the issue to your hosting provider, if they provide that kind of support. Also, if it's controllable per domain, you probably can disable it for Shaarli.

Please reopen this issue if you're able to provide a way to reproduce your problem.

**Comment by ShawnPConroy** [comment] 2017-12-25 20:47
You are correct and I now know of two work arounds, including one cPanel configuration at my host provider that turns off caching per domain or subdomain.

If you are curious to do testing I can setup FTP access or even cPanel access, but this has been resolved to my satisfaction. Though I feel Shaarli should work with caching, as almost all other software does.

Thanks to everyone who helped.

**Comment by nodiscc** [comment] 2018-01-17 20:39
> You are correct and I now know of two work arounds, including one cPanel configuration at my host provider that turns off caching per domain or subdomain.

Reopening this issue as a reminder to update https://github.com/shaarli/Shaarli/blob/master/doc/md/Troubleshooting.md with said workaround. @ShawnPConroy feel free to tell us about that second workaround :)

**Comment by ShawnPConroy** [comment] 2018-01-18 16:18
There are two fixes I found for cache issues.

The best way is to turn the feature off. On my hosting cPanel account I noticed a 'Cache Settings' menu items. A quick search showed it's sometimes called [Cache Manager](https://www.inmotionhosting.com/support/website/cpanel/nginx-plugin-for-cpanel) or [other more specific plugin names](https://docs.redy.host/knowledge-base/configure-efficient-caching-nginx-cpanel/). From there you can typically turn it off per domain or subdomain.

The alternative solution is to find out what your host provider uses to bypass the cache. For example, I can use port 8080 (http://yourdomain.com:8080/folder/) to get around it.

Those are the two work arounds I mentioned.

**Comment by ShawnPConroy** [comment] 2018-02-28 14:02
I regret to say that I may have been wrong. I cannot replicate the solution I said worked above. On my site Shaarli is not working at all. I reinstalled to the latest Shaarli, and with a new install and no data I still get the original issue:

It does nothing when it should display the new/edit dialogue.

ArthurHoaro commented on Nov 18, 2017 asking me to dump some variables. I get this perplexing set:

string(8) "linklist" array(0) { } array(0) { }

http://MYDOMAIN.ca:8080/?post=https%3A%2F%2Fgithub.com%2Fshaarli%2FShaarli%2Fissues%2F1027#

In theory this could be cache related, but I have disabled the cache.

**Comment by ArthurHoaro** [comment] 2018-02-28 18:06
These are really strange results, because `$_GET` (meaning detected query parameters) is empty, while your URL clearly shows query parameters...

> If you are curious to do testing I can setup FTP access

I can take a look if you can setup an empty Shaarli with FTP access. My email is on my Github profile.

**Comment by ShawnPConroy** [comment] 2018-03-02 15:45
Email sent.

**Comment by ArthurHoaro** [comment] 2018-05-21 16:58
Closing due to lack of (email) feedback, and it doesn't seem related to Shaarli. Here is my email from 2018-03-06:

> It looks like you have some sort of URI security enabled. I'm not sure
> if it's your actual issue or if it's only related to the test
> environment, but it definitely looks suspicious.
> 
> As soon as I have "http://" URL encoded in the query string, I get a 403
> Forbidden error. I've commented out the code retrieving the remote
> title, just to make sure it wasn't the issue.
> 
> Example :
>   * 403 :
> http://testserver.partialsolution.ca/shaarlitestfolder/index.php?post=http%3A%2F%2Fgithub.com#
>   * OK :
> http://testserver.partialsolution.ca/shaarlitestfolder/index.php?post=whatever
>   * Even OK (not url encoded) :
> http://testserver.partialsolution.ca/shaarlitestfolder/index.php?post=http://hi
> 
> I don't know if you can change anything regarding this or if it's on
> your host provider side.

**Closed by ArthurHoaro** 2018-05-21 16:58 UTC
Labels: documentation, server, support
