### ISSUE TITLE
One click bookmarklet [feature request]

### ISSUE THREAD

**Issue by philippejadin** [shaarli/Shaarli#1919] opened 2022-12-01 08:36 UTC
Long time user of shaarli here, first than you everyone involved!

I miss one functionality in shaarli, sometimes I just want to quickly keep a link without adding any information to it. The same as when you click on the wallabag browser extension : one click, your link is saved.
Same for the "star" feature of firefox.

Would it be possible to design an additional bookmarklet that when clicked, would open a small window which would save and autoclose?

I guess the way to do it would be to : 

- add a parameter to the /share endpoint, something like autosave=1 -> it would save and self close immediately
- create a new bookmarklet that would use this parameter.

I could work on it if it seems a good idea to the group.

**Comment by nodiscc** [comment] 2022-12-04 12:10
Duplicate of https://github.com/shaarli/Shaarli/issues/1704

**Closed by nodiscc** 2022-12-04 12:10 UTC
