### ISSUE TITLE
Bold text is not properly displayed when the Roboto font is installed locally

### ISSUE THREAD

**Issue by lionneye** [shaarli/Shaarli#1932] opened 2023-01-09 17:33 UTC
Hello,
Since few months already, despite using markdown syntax for bold text in my shaarli instance, it is not displayed as bold. For italic and others it works fine. It was working fine and then from one day to the other (or at least without that I noticed what had changed), it stopped working.
I ignored this until now. Now, I'm trying to solve it.
I think the problem is coming because of the browser used. I'm using Google Chrome. I've tried Microsoft Edge, same issue. With Firefox it works fine.
I looked for existing reported issues without finding it.
I've checked the shaarli [demo instance](https://demo.shaarli.org/) and from there as well in Google Chrome, the bold text is not properly displayed.
![image](https://user-images.githubusercontent.com/1142655/211369946-35a60043-5ca5-406f-a82d-bc767fb22c92.png)

Is there any recommendation for solving this display issue?

Thank you,
Jessica

**Comment by kcaran** [comment] 2023-01-09 18:52
Hi. The issue is in the font-face definition for Roboto Bold. If you have Roboto locally you'll get the regular weight instead of bold. I don't you would see it if you downloaded the font instead:

mail:/var/www/shaarli/assets/default/scss$ git diff shaarli.scss
diff --git a/assets/default/scss/shaarli.scss b/assets/default/scss/shaarli.scss
index cc8ccc1e..67541ae8 100644
--- a/assets/default/scss/shaarli.scss
+++ b/assets/default/scss/shaarli.scss
@@ -81,7 +81,6 @@ pre {
   font-weight: 700;
   font-style: normal;
   src:
-    local('Roboto'),
     local('Roboto-Bold'),
     url('../fonts/Roboto-Bold.woff2') format('woff2'),
     url('../fonts/Roboto-Bold.woff') format('woff');

If you change the assets/default/scss/shaarli.scss file and run 'make build_frontend', it should fix the tpl/default/css/shaarli.min.css file.

I could create a pull request but I'm not sure how the demo site gets updated.

**Comment by lionneye** [comment] 2023-01-10 11:02
Hello,
Thank you very much for your input!! Your suggestion was too technical for me but you point to the problematic usage of local Roboto font. Then by uninstalling this font from my PC it works now. Maybe I could have downloaded a new version of the font as well but I was not specially interested for keeping this font.

**Comment by nodiscc** [comment] 2023-01-24 12:42
Thanks for reporting this. I can reproduce on the demo instance and my own instance. I can confirm @kcaran's patch fixes the problem (`local('Roboto'),` shouldn't be there for this `@font-face` definition - removing it from the minified CSS fixed the problem on my instance)

> I could create a pull request

Please do!

> I'm not sure how the demo site gets updated

As far as I know the demo site automatically updates from the latest `master` every day.

**Comment by nodiscc** [comment] 2023-01-29 23:26
Fixed in https://github.com/shaarli/Shaarli/pull/1936

**Closed by nodiscc** 2023-01-29 23:26 UTC
Labels: bug
