### ISSUE TITLE
Unable to delete links on Firefox Mobile on iPhone

### ISSUE THREAD

**Issue by jmlrt** [shaarli/Shaarli#585] opened 2016-06-05 14:30 UTC
Hi,

When I browse my Shaarli from Firefox Mobile on iPhone, I can't delete the links.
If I click on the garbage to delete a link, I have the "Are you sure you want to delete this link?" popup. When I click on OK, the popup disappears but the link isn't deleted.

When I use Safari or Chrome Mobile. the links can be deleted.

**Comment by ArthurHoaro** [comment] 2016-06-06 15:17
Couldn't reproduce with Firefox 46.0.1 on Android.

I suspect there is something odd going on with the combination POST image button and the JS alert. I wanted to switch to a GET parameter (simple linked image/icon instead of a button) with the new webdesign anyway.

**Comment by ArthurHoaro** [comment] 2017-03-11 13:17
Fixed by the new template

**Closed by ArthurHoaro** 2017-03-11 13:17 UTC
Labels: browser, bug, enhancement, support, template
