### ISSUE TITLE
After logging in, can't view anything - "You must specify an integer as a key"

### ISSUE THREAD

**Issue by cjrobe** [shaarli/Shaarli#854] opened 2017-05-02 13:58 UTC
I can look at all my links as a guest but when I login it just shows a blank white page that says "You must specify an integer as a key."

I upgraded from a version more than a year old. My old index.php file has a date of 2/17/2016. I only moved over my datastore.php, I ran the config file again. In [this thread](https://github.com/shaarli/Shaarli/issues/847) that was resolved by deleting a txt file I don't have, it was mentioned that "Your datastore hasn't been updated as it should have been since v0.8.1."

Is there a specific version I should run first to update my datastore?

Thanks and sorry if I missed something obvious.

**Comment by ArthurHoaro** [comment] 2017-05-03 16:15
Hi, no you didn't miss anything, your datastore should update no matter what version you're upgrading from. Looking at the release dates, you were probably using v0.6.3, I'll give it a try.

Can you confirm that you're upgrading to v0.8.4?

In any case, save your original datastore.

**Comment by ArthurHoaro** [comment] 2017-05-03 16:27
OK, this is actually a duplicate of #775. I thought we fixed it but I only provided a workaround. I'll provide a patch before the next release.

**Comment by ArthurHoaro** [comment] 2017-05-03 17:17
Oh I thought I was going crazy but I've already fixed that, it's just not released yet.

**Closed** 2017-05-03 17:17 UTC
Labels: bug, support

**Comment by cjrobe** [comment] 2017-05-20 16:20
For some reason I didn't receive notifications for this, sorry. The fix from the thread with the updates.txt file work, thanks!
