### ISSUE TITLE
Option to add link in menu for iframed external page?

### ISSUE THREAD

**Issue by poVoq** [shaarli/Shaarli#1078] opened 2018-02-07 04:56 UTC
Is there a relatively easy way to add a link in the top menu to link to an external page in an iframe?

For now I have manually edited the theme to add an external link, but being able to add this from the Shaarli configuration menu would be great, especially if it would allow keeping the top menu visible and load the external page in an iframe below it.

Thanks for considering it or giving me some tips how I can manually add this.

**Comment by ArthurHoaro** [comment] 2018-02-07 18:25
For the configuration part, your request is a duplicate of #359.

About addind custom stuff in the header, such as an iframe, it is not supported yet. And it probably won't be as any solution would be theme dependant. However, using a custom javascript, loaded in a plugin, which interacts with the DOM may let you achieve that.

**Closed** 2018-02-24 18:07 UTC
Labels: duplicate, plugin, question
