### ISSUE TITLE
BUG: QR-Code generate works sometimes

### ISSUE THREAD

**Issue by Dtrieb** [shaarli/Shaarli#1745] opened 2021-05-05 18:59 UTC
I didn't understand that:
Sometimes i can generate a QR-Code on my Desktop with the newest Chrome Browser, sometimes not.
With my Android Phone Chrome Browser it always works.

Any Ideas?

**Comment by ArthurHoaro** [comment] 2021-05-05 19:08
Do you have any error in your browser console log when it doesn't work?

**Comment by ArthurHoaro** [comment] 2021-05-08 12:01
I can't reproduce your issue and that error *should* not have any effect on the actual behavior of the script.

  * What's your Chrome version?
  * Do you reproduce that issue on demo.shaarli.org?

**Comment by nodiscc** [comment] 2022-08-10 18:28
No reply for a year, closing.

**Closed by nodiscc** 2022-08-10 18:28 UTC
Labels: bug, unconfirmed

**Comment by Dtrieb** [comment] 2023-04-23 19:00
> * What's your Chrome version?
Version 112.0.5615.138 (Offizieller Build) (64-Bit)
> * Do you reproduce that issue on demo.shaarli.org?
No it work on the demo version
