### ISSUE TITLE
Regression: Shaarli does not show link title as page title anymore if single link is opened

### ISSUE THREAD

**Issue by fbartels** [shaarli/Shaarli#399] opened 2015-12-05 08:45 UTC
Hi,

in the past when directly opening a link the title of this link was displayed as the page title.

For example http://shaarlidemo.tuxfamily.org/Shaarli/?I8Q0Og only shows "demo", but used to show "demo - Shaarli: the personal, minimalist, super-fast, no-database delicious clone".

I did not investigate this further yet, but this behaviour changed for me on the 19th of november (probably by pulling in changes with git), but I don't know which revision I was running before.

**Comment by ArthurHoaro** [comment] 2015-12-05 10:02
Confirmed.

Page title is relying on a global variable and lazy loading instantiation (!). The plugin system instantiate the page builder before the title is set. I'll provide a quick fix.

Also, @virtualtam is working on a refactoring with #397 which would prevent this to happen again. :)

**Comment by fbartels** [comment] 2015-12-05 14:31
Hi,

thanks for looking into this. I can confirm that after applying your patch headers are shown again.

**Comment by virtualtam** [comment] 2015-12-06 21:35
Actually, after merging the fix, the title is not set on the main page O_o

Page titles are set as globals, so when and how they're assigned is quite hard to track - #397 won't solve all the problems, but should give a good starting point to control what's passed to templates.

The confusion comes from the following variables:
- `$GLOBALS['title']`: title of the Shaarli instance
- `$GLOBALS['pagetitle']`: always empty, _except_ when accessing a permalink's page, in case it evaluates to `<title of the link> - <Shaarli title>`

I suggest the following to address it properly:
- revert #400
- proceed on #397 to have a unified way of parameterizing templates, useable by plugins
- merge `title`-related variables, add explicit processing when setting the page title when a sole link is displayed

**Comment by ArthurHoaro** [comment] 2015-12-07 09:32
Instead of reverting #400, I've provided another fix. I made more tests this time... This is only temporary anyway, but I'd rather keep the master branch as bug free as possible.

**Comment by ArthurHoaro** [comment] 2015-12-14 19:44
Closing, because technically fixed with #405. 

#397 will provide a more permanent solution.

**Closed by ArthurHoaro** 2015-12-14 19:44 UTC
Labels: bug
