### ISSUE TITLE
Documentation build fails due to deprecation warnings in MkDocs

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#1179] opened 2018-07-12 20:03 UTC
https://readthedocs.org/projects/shaarli/builds/7478574/

```
python /home/docs/checkouts/readthedocs.org/user_builds/shaarli/envs/master/bin/mkdocs build --clean --site-dir _build/html --config-file /home/docs/checkouts/readthedocs.org/user_builds/shaarli/checkouts/master/mkdocs.yml --theme readthedocs
WARNING -  Config value: 'theme_dir'. Warning: The configuration option {0} has been deprecated and will be removed in a future release of MkDocs. 

Aborted with 1 Configuration Warnings in 'strict' mode!
Command time: 0s Return: 1
```

**Comment by virtualtam** [comment] 2018-07-12 22:08
Looks like a RTFD-specific issue, I cannot reproduce it locally using the Python and package versions logged by the build:

```shell
$ pew new -p python2 mkdocs2
$ pip install --upgrade Pygments==2.2.0 'setuptools<40' docutils==0.13.1 mock==1.0.1 pillow==2.6.1 'alabaster>=0.7,<0.8,!=0.7.5' commonmark==0.5.4 recommonmark==0.4.0 mkdocs==0.17.3
# [...] pip doing pip stuff
$ mkdocs build -c
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/virtualtam/dev/shaarli/shaarli/doc/html
```

**Comment by virtualtam** [comment] 2018-07-12 22:09
Related:
- https://github.com/rtfd/readthedocs.org/issues/4231
- https://www.mkdocs.org/about/release-notes/#stricter-directory-validation

**Comment by virtualtam** [comment] 2018-07-12 22:21
Yup, looks like RTFD passes outdated configuration options :(

From the [raw build logs](https://readthedocs.org/api/v2/build/7478574.txt):

```yaml
site_dir: doc/html
site_name: Shaarli Documentation
strict: true
theme: readthedocs
theme_dir: /home/docs/checkouts/readthedocs.org/readthedocs/templates/mkdocs/readthedo
```

From [MkDocs - Configuration - Build Directories](https://www.mkdocs.org/user-guide/configuration/#build-directories):

```yaml
theme:
    name: mkdocs
    custom_dir: my_theme_customizations/
    static_templates:
        - sitemap.html
    include_sidebar: false
```

**Comment by virtualtam** [comment] 2018-07-24 17:52
Builds are now passing with a warning:
- https://readthedocs.org/api/v2/build/7536503.txt

It looks like RTD has disabled the `strict` flag to allow MkDocs-based build to succeed, see https://github.com/rtfd/readthedocs.org/issues/4314

@nodiscc should we close this issue?

**Comment by ArthurHoaro** [comment] 2018-07-25 06:29
My understanding of this thread, is that disabling the `strict` flag is a quick workaround to get MkDocs build to pass. If it is now passing, I don't see any advantage of disabling it. We should rather wait for RTD to fix their theme issue.

**Comment by virtualtam** [comment] 2018-07-28 10:37
Closing for now, feel free to reopen when changes are made to ReadTheDocs' build process

**Closed by virtualtam** 2018-07-28 10:37 UTC
Labels: bug, documentation, tools
