### ISSUE TITLE
Plugin suggestion: add links to Shaarli Menu

### ISSUE THREAD

**Issue by VLNTNO** [shaarli/Shaarli#1137] opened 2018-05-11 15:04 UTC
Hi folks,

I have hacked the shaarli code to add an important link of my shaarli to the user menu (the menu displayed once connected).

With the new concept of assets/themes, I'll be able to have the modifications on the View side, but...

Could there be a plugin, or a setup, to allow adding to this User menu a list of links without modifying the code?

This could help easily displaying a link to a summary, to an index, or something else.

Thanks and best regards

Valentin

**Comment by ArthurHoaro** [comment] 2018-05-12 09:12
Hi, if I understand correctly, I think your request might be a duplicate of #359.

**Comment by VLNTNO** [comment] 2018-05-12 17:07
Yes, looks like it can be done via a plugin. I'll investigate this way.
Thank you, and sorry if I made you lost your time...
A+

**Comment by ArthurHoaro** [comment] 2018-05-13 10:37
No worries, this feature request has been on hold for a while...

**Closed by ArthurHoaro** 2018-05-13 10:37 UTC
