### ISSUE TITLE
Enhancement: Multi word tags

### ISSUE THREAD

**Issue by dfear** [shaarli/Shaarli#594] opened 2016-07-06 15:08 UTC
Please support multi word tags, just like delicious does. 

> [EDIT 2016-07-07 by virtualtam]
> Relates to / duplicates:
> #70 - Comma-separated tags
> #145 - Manage tags with space

**Comment by ArthurHoaro** [comment] 2016-07-06 15:57
What's the avantage of multi word tags over the current system?

**Comment by virtualtam** [comment] 2016-07-06 16:19
@dfear how would you define _multi word tags_? (It's worth mentioning that most Shaarli users/devs have never used Delicious & al.)

As far as I understand it, it would correspond to an ordered group of keywords, in which case a search for _multi word tagged_ links would return results that are tagged with these specified words, in this particular order.

**Comment by dfear** [comment] 2016-07-06 16:24
Here is an example:
Example tag: "gnome shell extensions google chrome"

in delicious they would be stored/shown as:
gnome shell, extensions, google chrome

but shaarli would stored/show them as
gnome, shell, extensions, google, chrome


in delicious when you type a comma, a new tag is created.

I think your definition is correct.

**Comment by virtualtam** [comment] 2016-07-06 16:34
OK, so this would mean that Delicious has a tag management system, to know which group of words correspond to a unique tag.

In Shaarli, this can be reproduced by using `CamelCase` or `dash-separated` tags; though this could be an issue when importing a collection of links from Delicious to Shaarli.

**Comment by alexisju** [comment] 2016-07-06 16:38
When i have migrated my links from Delicious to Shaarli, this missed me also. This gave me a lot a work to clean my links from wrong tags (because tags with space were imported as several tags what gave weird things (like duplicate tags or irrelevant tags).

I was also used to use comma between tags, and i still thinking it is more logicial than spaces.

**Comment by dfear** [comment] 2016-07-06 16:49
CamelCase or dash-separated tags would work for me as I am migrating from delicious and have 6000 links to import.

**Comment by virtualtam** [comment] 2016-07-06 17:05
This actually looks more like an import/interoperability issue than search feature request :)

I'm currently working on a replacement for the bookmark import(er) at https://github.com/shaarli/netscape-bookmark-parser ; this parser will soon (a few weeks) be integrated to Shaarli and could be customized to modify links on-the-fly, e.g. replacing multi-word tags by their CamelCase or dash-separated counterparts.

Could you provide us with a sample export from Delicious featuring links with both single- and multi-word tags?

**Comment by ArthurHoaro** [comment] 2016-07-06 17:20
That's definitely an issue. Multi word tags are debatable, but I'm not really in favor of that, since the current tag system is very simple and powerful. However, adding an option to import comma separated tags, and convert them, is doable. What do you think @virtualtam?

**Comment by virtualtam** [comment] 2016-07-06 17:30
I'd go towards improving parsing features so bookmarks imported from other services can be converted to a format that can then be easily managed by Shaarli (i.e. without reworking the internals such as storage and search).

This is a rather generic issue, as any given bookmarking service might store and export bookmark collections in a flavoured format.

**Comment by Marsup** [comment] 2016-07-06 17:43
This feels very unnatural for anyone who used a tagging system before (not only on bookmarks related), as I can't think of any system that didn't support commas as separator. This is not only an import problem, this is a usability problem, as when you type tags, it's almost muscle memory to type spaces, you never go for dashes or underscores, even less camel casing. I don't want to jump to conclusions, but I think this project is an exception in the tagging landscape, which is precisely what's destabilizing.

**Comment by virtualtam** [comment] 2016-07-06 18:29
> this project is an exception in the tagging landscape, which is precisely what's destabilizing

The issue is, adding the stabilizers means:
- rewriting the tagging system to use commas as a delimeter
- updating link filtering (search)
- adding a backwards-compatibility / migration process not to break every user's instance
- maybe allowing users to define a custom delimeter?

Whereas converting tags to the current format can be simply done by modifying the import parser. This may not be optimal from a usability point of view, but provides a working tradeoff that can be easily developed.

Unless, of course, if someone is interested in working on this feature, in which case we'll be happy to provide dev support ;-)

![](https://s-media-cache-ak0.pinimg.com/236x/79/37/7e/79377e1fecaf7185606e30a071fed35c.jpg)

**Comment by alexisju** [comment] 2016-07-06 19:48
This still an issue (for some) since 2012... at least : http://sebsauvage.net/wiki/doku.php?id=php:shaarli:discussion#comment_1de251b8b80759ca538b48ba57fff4fa

Others related closed issues (but not resolved) about this : #145, #70

**Comment by virtualtam** [comment] 2016-07-06 21:01
As understated by my previous comment: I do not question whether this need is valid or not, but we both lack the time to tackle it, and have other priorities in terms of which features are brought in the next releases, hence the easy-to-implement replace-spaces-with-dashes proposition.

I'd suggest we keep this issue open (or raise a new one) to discuss and define how tag handling should be improved/overhauled, and get it done when someone has the time and interest to work on it.

ping @ArthurHoaro @nodiscc

**Comment by Marsup** [comment] 2016-07-06 21:53
I have about zero knowledge in PHP, but is there any reason why the tags are stored as a string and not an array ? You constantly have to explode it.

**Comment by virtualtam** [comment] 2016-07-06 22:20
Internally, the tags are stored as an array, which means they are:
- exploded before storage
- imploded and joined by a space for display

There is no specific reason behind this; it has been implemented this way in the first place, and now is part of the legacy code: worth rethinking/refactoring to better fit user needs, but not a top priority (see #324) :)

**Comment by nicolasdanelon** [comment] 2016-07-07 01:26
-1 hash tags should be a world. like Twitter or Facebook hash tags..

**Comment by Marsup** [comment] 2016-07-07 07:20
-1 to that -1 :) There's a pretty good reason they have hashtags, they only have a single input field, it makes no sense with the current shaarli design to have that, also it doesn't solve the space problem at all.

**Comment by dper** [comment] 2016-07-07 07:55
I imagine many users (such as myself) are happy with the current behavior. A change to commas instead of spaces would require we adjust our tagging habits. Are the gains particularly significant?

**Comment by Marsup** [comment] 2016-07-07 10:32
The ability to have a more natural way to express oneself on the tagging system, I've personally been forced many times to find alternative tag names or underscore the tags when I couldn't.

**Comment by virtualtam** [comment] 2016-07-07 11:09
> I'd suggest we keep this issue open (or raise a new one) to discuss and define how tag handling should be improved/overhauled, and get it done when someone has the time and interest to work on it.

If everyone's OK with this, I'll raise a new series of issues to improve tag handling:
- import: update the _parser_ & improve support for _comma-separated, multi-word tags_
- UI/settings: allow the _user_ to specify the _tag delimiter_ in the input fields
- link storage: be more flexible
- export: ensure links can be exported in a suitable format

The goals being:
- keeping the current behavior as default, not to break existing Shaarlis
- providing more flexibility for those who want/need it

I'll try to address it once the new import parser has been integrated :)

_Help_ will be much _appreciated_, by:
- providing bookmark dumps from Delicious
    - by extension, from any other bookmarking service allowing exports using the Netscape format
- raising new issues on https://github.com/shaarli/netscape-bookmark-parser
    - attach/embed bookmark dumps
    - this will help writing unitary tests to ensure links are properly parsed, and the input data not altered

**Comment by ArthurHoaro** [comment] 2016-07-09 05:13
I'm OK with your propositions. Note that this will also affect awesomplete script.

**Comment by kalvn** [comment] 2016-07-12 10:01
And potentially some externally-managed applications (such as those for Android or iOS).

**Comment by nicolasdanelon** [comment] 2016-07-15 13:06
@marsup more natural way? no body is saving `linux bash git` as a tag.. those are 3 tags! Shaarli tags should be single words! `linux` `bash` `git`
the current behavior is so easy and fast.. would be awesome if some freaking crazy guys who want to have this could enable it.. I love to read virtualtam comment

**Comment by Marsup** [comment] 2016-07-15 13:39
Then make it an option, just because you don't have the need doesn't need others don't.

**Comment by nodiscc** [comment] 2016-07-15 14:09
To recap this particular issue, 

 - [ ] allow tag separators to be customized.

This is a long-standing request as far as I remember (#70, #106...). The default separators (whitespace and comma) would be left untouched. A configuration setting would allow removing the whitespace and/or adding other separators.

We should be extra careful to prevent accidental changes of this setting.

Right?

**Comment by Marsup** [comment] 2016-07-15 14:15
Why not an array of allowed separators which would default to [' '] ?

**Comment by nodiscc** [comment] 2016-07-15 14:19
@Marsup current defaults would be `[' ', ',']`

**Comment by kalvn** [comment] 2016-07-15 14:47
There could be an issue with users who already used the comma in existing tags (even though I agree, comma is not a good candidate for a tag name).

Otherwise, to get around this problem (although I don't know if tags are stored as a plain string or as an array of string) we could add a small Javascript helper a bit like what Grav does for example:

![Animated gif illustrating the tag system in Grav](http://i.imgur.com/oNtFzPp.gif)

It creates a tag block each time you click on the "Add..." link below, hit the ENTER key or hit the comma key. It therefore authorizes spaces (but obviously not commas) within tags.

The counterpart of it is that it would make things more difficult for third party software such as mobile applications.

**Comment by nodiscc** [comment] 2016-07-16 08:37
> There could be an issue with users who already used the comma in existing tags 

@kalvn The `,` is already a tag separator by default in current Shaarli so there would be no changes.

> we could add a small Javascript helper a bit like what Grav does 

This can be reported in another issue if needed. But I'd say keep it simple.

**Comment by kalvn** [comment] 2016-07-18 14:42
I agree. It may be a good plugin candidate though. I'll think about this.

**Comment by sijnak** [comment] 2016-11-26 20:02
Hello,

I made changes back in 2013 to Sebsauvage's Shaarli to allow tags to be separated by a user-defined separator. And then I never worked on this again. Now I would like to give it a second try. (Disclaimer: I might very well get bored and not finish this task.)

@virtualtam shall I create the issues for each sub-task as you suggested ?

I'm considering to store the tags as a table, abstracting the database from the separator. One could then chose a number of separators (including a default one) which would be used for display and insertion/update of links. The default separator would be used for the display of links.

Does it sound OK ?

**Comment by ArthurHoaro** [comment] 2016-11-27 00:09
> I'm considering to store the tags as a table

You should go with an array per link, otherwise you may have problems with Shaarli's current storage mechanism: the "database" is a single array.

Also, how do you see the settings UI? I'd like to keep it simple.

**Comment by sijnak** [comment] 2016-11-27 10:11
Well, my plan was to actually "upgrade" the database, if it is not too much. I thought that instead of a string at index "tags" in the database, we could have an array. This way, handling the separator is no longer the database's concern.

As for the settings UI, I have no idea yet. Do you have a prefered way ?

I also wonder about tag separator definition. Should they be all defined in a regex (powerful but not user-friendly) or a string/array of single characters ?

**Comment by ArthurHoaro** [comment] 2016-11-28 09:16
> I thought that instead of a string at index "tags" in the database, we could have an array. 

That's exactly what I meant. :-)

Maybe a single text field with the list of delimiters would be enough. Not super user friendly but efficient. Someone may have a better idea.

I'd say an array of characters in the JSON file is fine.

**Comment by sijnak** [comment] 2016-12-02 22:19
OK, great. I'm slowly working in this direction.

**Comment by sijnak** [comment] 2016-12-03 10:41
I face some problem with the Javascript/HTML side. I know too little of both to be confident to find a good solution. Here it comes

Awesomplete can manage tags with custom separator but I don't know how to get it to know what separator was set in the configuration of Shaarli. I mean that a custom string has to be conveyed from PHP configuration to javascript code. For instance, in `inc/awesomplete-multiple-tags.js` at lines 4 and 8.

Could someone help me on that ?

**Comment by ArthurHoaro** [comment] 2016-12-03 10:48
Hmm. That's a bit tricky. Variables are passed to templates using RainTPL variables. So using permissive JS scope, you can probably do:

```
<script>var separators = {$raintplSeparator};</script>
<script src="inc/awesomplete-multiple-tags.js#"></script>
```

and use `separators` in `inc/awesomplete-multiple-tags.js`.

**Comment by sijnak** [comment] 2016-12-03 11:04
Thanks, I'll give it a try

**Comment by effemmeffe** [comment] 2017-02-10 08:11
For what it worth I second this request.
I have a Moto G and a Nexus 7 and some links on my old deliciuos were tagged as "android" "moto g" and some others are "android" "nexus 7". After importing I had to remove all those tags "g" and "7".

**Comment by Lucas-C** [comment] 2017-04-17 22:24
Allowing spaces in tags would be an awesome feature. Any progress on this ?

**Comment by sijnak** [comment] 2017-04-18 16:37
I have started to work on such version of Shaarli and the result of this work is in #849. I'm working on resolving the requested changes and hope that it could be merged soon.

**Comment by Lucas-C** [comment] 2017-04-20 06:23
Great ! Thanks a lot :)

**Comment by jodumont** [comment] 2018-05-27 10:58
Before reading all the comments, I was surprise this feature wasn't already supported and of course I found this issue by G**gle how to do it, but after reading all comment, I become with 2 points of view.

-----

## Against
The comment of @nicolasdanelon about keyword must be only one keyword make sense because `in Shaarli you could filter by multiples tags` which if you use keyword with multiple words you might miss links in your research.

## For
If the system permit to use multiple words via a delimiter like `'Keyword1 Keyword2'` or `Keyword1+Keyword2` or `,Keyword1 Keyword2,` and you don't like it, than just don't use it.

-----
Now sadly I'm not a developer and the only thing I could do is cheering the commitment of those maintain this awesome app.

**Comment by xrat** [comment] 2018-05-27 13:17
For now, for some, maybe, a simple workaround might be to use [Unicode non-breaking spaces](https://en.wikipedia.org/wiki/Non-breaking_space). I did a quick test on one of my 0.8.6 installations. Basic operation seemed to work just fine. Of course, it's just a dirty workaround.

**Comment by ArthurHoaro** [comment] 2020-10-21 14:25
I'm going to work on this. The idea is to allow users to change the tags separator character on ones Shaarli instance. The whitespace character will remain the default one.

What needs to be checked to prevent regressions:

  - [ ] updating the separator doesn't break existing bookmarks
  - [ ] import system
  - [ ] export system
  - [ ] front-end JS autocomplete (bookmark form, search, tag list, etc.)
  - [ ] no behavior change in the REST API (3rd party tools can handle the format in their own front end)
  - [ ] RSS feeds
  - [ ] Bookmark metadata retrieval (both sync and async)

**Closed** 2020-11-08 13:07 UTC
Labels: enhancement, tags
